[project]
name = "python-crypto-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "python-dotenv>=1.1.0",
    "ruff>=0.9.7",
    "sqlalchemy>=2.0.38",
    "websocket>=0.2.1",
    "websocket-client>=1.8.0",
    "websockets>=15.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
[tool.pytest.ini_options]
pythonpath = "src"

[tool.uv.workspace]
members = ["cryptotrader"]
